# ===================================================================
# Standard Spring Boot properties
# ===================================================================
spring:
    profiles:
        active: dev
    main:
        banner-mode: "off"
    jpa:
        properties:
            hibernate:
                generate_statistics: false
                order_inserts: true
                order_updates: true
                temp:
                    use_jdbc_metadata_defaults: false
                jdbc:
                    batch_size: 10
                    time_zone: UTC
                enable_lazy_load_no_trans: false
    datasource:
        hikari:
            connectionTimeout: 50000
            idleTimeout: 300000
            maxLifetime: 900000
            maximumPoolSize: 10
            minimumIdle: 8
            poolName: AccelenginePool
            autoCommit: false
            connectionTestQuery: select 1
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
                useLocalSessionState: true
                rewriteBatchedStatements: true
                cacheResultSetMetadata: true
                cacheServerConfiguration: true
                elideSetAutoCommits: true
                maintainTimeStats: false
    resources:
        add-mappings: false
    mvc:
        throw-exception-if-no-handler-found: true
    http:
        encoding:
            force: true
    servlet:
        multipart:
            max-file-size: -1
            max-request-size: -1B
server:
    error:
        include-stacktrace: NEVER
#  ssl:
#    enabled: false # change it to true to force HTTPs in embedded tomcat
#    key-store-type: PKCS12
#    key-store: classpath:keystore/accelengine.p12
#    key-store-password: accelengineDiscovery2021MH
#    key-alias: accelengine

# ===================================================================
# Application specific properties
# Add Application properties here, see the MegProperties class
# ===================================================================

application:
    name: PFE
